base:
  project: dvc_pipeline_demo
  random_state: 47
  target_col: diagnosis

data_source:
  # gs_path: gs://dvc_project/
  local_path: C:\Users\awscl\OneDrive\Desktop\project_DVC\Training_Batch_Files\data.csv

split:
  dir: data/split
  train_file: train.csv
  test_file: test.csv
  split_ratio: 0.30

process:
  dir: data/processed
  train_file: final_train.csv
  test_file: final_test.csv

train:
  n_est: 35
 
model_dir: model


